[package]
name = "sayho-bin"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
sayho = { path = "app" }
runtime = "=0.3.0-alpha.4"

[workspace]
